package com.aaa.web.page;

import org.openqa.selenium.By;

public class CRMemberSearchPage {
    public static By callTalker;
    public static By commentFeild;
    public static By loadingspinner;
    public static By mandaotryFields;
    public static By emptyResults;
    public static By iconResultLoadingSpinner;
    public static By lblMemberNumberColumnValue;
    public static By lblMemberContactColumnValue;
    public static By lblMemberNameColumnValue;
    public static By lblMemberAddressColumnValue;
    public static By lblMemberFirstName;
    public static By lblMemberLastName;
    public static By lblMemberNumberTxt;
    public static By lblMemberZipCode;
    public static By lblMemberState;
    public static By lblMemberCity;
    public static By txtMemberEmailId;
    public static By txtMemberPhone;
    public static By iConcurrentCallClose;
    public static By alertClose;
    public static By lnkManualEntryOnMember;
    public static By partialCall;
    public static By closeIconOnPartialCall;
    public static By alertCallsActiveBoxClose;
    public static By alertCallsActiveBox;
    public static By txtTitle;
    public static By clubCode;
    public static By txtFirstName;
    public static By txtLastName;
    public static By txtSuffix;
    public static By txtAddressLine1;
    public static By txtAddressLine1_Error;
    public static By txtAddressLine2;
    public static By txtCity;
    public static By txtState;
    public static By txtZip;
    public static By txtEmail;
    public static By txtMemberNumber;
    public static By txtMbrSince;
    public static By txtMemberLevel;
    public static By txtMemberType;
    public static By txtMemberExpiration;
    public static By txtMemberStatus;
    public static By txtPhone_NumberFirstRow;
    public static By txtPhone_NumberSecondRow;
    public static By txtPhone_NumberThirdRow;
    public static By txtPhoneType;
    public static By radiodbtnPrimRowOne;
    public static By radiodbtnPrimRowTwo;
    public static By memberTab;
    public static By alertUndefinedError;
    public static By errorAlertOK;
    public static By scriptError;
    public static By btnAlertSaveYes;
    public static By saveFailureError;
    public static By errorNotifications;
    public static By linkMemberId;
    public static By memberAddressInformation;
    public static By chkBoxDelCheckBoxSecondRow;
    public static By addPhoneButton;
    public static By linkCallPopupWindowCancel;
    public static By radiobtnPrimInRowThree;
    public static By chkBoxTempCheckBoxRowOne;
    public static By chkBoxTempCheckBoxRowThree;
    public static By dropDownPhoneTypeRowThree;
    public static By addPhoneNumberTextThirdRow;
    public static By addPhoneNumberTextFirstRow;
    public static By callsActiveBox;
    public static By lablMemberName;
    public static By errorNotification;
    public static By lblMemberShipNumber;
    public static By lblMemberSince;
    public static By lblMemberLevel;
    public static By lblMemberType;
    public static By lblMemberExpiration;
    public static By lblMemberStatus;
    public static By memberCallsAllowed;
    public static By memberCallsRemaining;
    public static By memberCallsUsed;
    public static By memberCurrentCalls;
    public static By memberChargeableCalls;
    public static By memberHistoryCalls;
    public static By txtScratchPad;
    public static By radiobtnChangeOfAddress;
    public static By iconcurrentcallClose;
    public static By rbutnprimary_phone;
    public static By txtMemberSience;
    public static By iconScratchPad;
    public  static By iconScratchPadClose;
    public static By listOfCallsID;
    public static By btnClubCodeSearch;
    public static By cityClubCode;
    public static By txtClubCode;
    public static By btnSearchButton;
    public static By listOfLastNames;
    public static By txthonorific;
    public static By lableExpirationDate;
    public static By iconSearchCallClose;
    public static By linkCallID;
    public static By expirationErrorMessageOKButton;
    public static By txtType;
    public static By txtSecondaryPhoneType;
    public static By membershipRenewAlert;
    public static By btnMembershipRenewNo;
    public static By btnMembershipRenewYes;
    public static By radiobtnPrimInRowTwo;
    public static By chkBoxSms;
    public static By confirmationDialogQuestion;
    public static By btnYesOnConfirmationDialogQuestion;
    public static By btnNoOnConfirmationDialogQuestion;
    public static By lblMemberCallId;;
    public static By txtRapCallNumber;;
    public static By txtRapPaymentResponsibilityCode;;
    public static By clubCodeSelectionForRAPCall;
    public static By txtLongTowAllowedValue;
    public static By lnkRapEntitlements;
    public static By txtPhoneNumberFirstRecord;
    public static By txtPhoneTypeFirstRecord;
    public static By verifyMemberCompleteCheck;
    public static By linkCallSummaryIconOnMemberspage;
    public static By phoneNumberOnCallSummaryPOPUp;
    public static By radiodbtnPrimRow;
    public static By lblCdxAuthorizationLevel;
    public static By lblCdxAuthorizationMessage;
    public static By lblCdxAuthorizationCode;
    public static By lblCdxMotorCycleCoverage;
    public static By errorServiceUnavailable;
    public static By errorCDXServiceUnavailable;
    public static By txtLiveCall;
    public static By lblMemberNameOnManualEntry;
    public static By lblAddressOnManualEntry;
    public static By lblAddress2OnManualEntry;
    public static By lblCityOnManualEntry;
    public static By lblStateOnManualEntry;
    public static By lblZipOnManualEntry;
    public static By lblMemberShipNumberOnManualEntry;
    public static By lblMemberSinceOnManualEntry;
    public static By lblLevelOnManualEntry;
    public static By lblTypeOnManualEntry;
    public static By lblExpirationOnManualEntry;
    public static By lblStatusOnManualEntry;
    public static By lblEmailOnManualEntry;
    public static By lblPhoneInformationOnManualEntry;
    public static By listOfLoadedCalls;
    public static By lnkcallIdOnLoadedCallList; 
    public static By txtPhoneNumber;
    public static By enterPhoneNumber;
    public static By clickPrimRadiobutton;
    public static By selectTempDeleteChkBox;
    public static By selectPhoneType;
    public static By lblDateInMemberPage;




    static {
        //Member Tab Locator
        memberTab = By.id("tab-member");
        //lnkManualEntryOnMember = By.xpath("//a[contains(@id,'member-manual-entry-a-link')][contains(text(),'Manual Entry')]");
        lnkManualEntryOnMember = By.id("member-manual-entry-a-link");
        memberAddressInformation = By.xpath("//*[@id='search-results']/tbody/tr/td[5]");
        alertCallsActiveBoxClose = By.cssSelector("div span[id='ui-dialog-title-callsactive-box']+a span");
        alertCallsActiveBox = By.cssSelector("div span[id='ui-dialog-title-callsactive-box']");
        partialCall = By.cssSelector("span[id='ui-dialog-title-confirmation-box']");
        callsActiveBox = By.xpath("//*[contains(text(),'Current calls for')]");
        alertClose = By.xpath("//*[contains(@id,'ui-dialog-title-callsactive-box')]//..//*[contains(@class,'ui-icon-closethick')]");
        scriptError = By.id("scripts-immediate-dialog-okayBtn");
        btnAlertSaveYes = By.id("confirmation-yes-btn");
        iConcurrentCallClose = By.cssSelector("div span[id=\"ui-dialog-title-callsactive-box\"] +a span");
        iconResultLoadingSpinner = By.id("d3ui-loading-spinner");
        loadingspinner= By.id("d3ui-preloader-loadingtext");
        emptyResults = By.cssSelector("div table[id='search-results'] tbody tr td[class='dataTables_empty']");
        mandaotryFields = By.xpath("//*[contains(@class,'d3ui-required')]"); //
        txtScratchPad=By.id("scratchpad-text-area");
        iconScratchPad=By.xpath("//a[@title='Scratch Pad']/i");
        iconScratchPadClose =By.cssSelector("span[id='ui-dialog-title-scratchpad-dialog']+a");
        callTalker = By.xpath("//span[contains(@class,'d3ui-unified-header-username')][contains(text(),'calltaker')]");
        commentFeild = By.xpath("//textarea[@id='comment-input']");
        clubCode = By.id("club-active-code");
        txtPhone_NumberFirstRow = By.xpath("//*[@id='phone_number']");
        //txtPhone_NumberFirstRow = By.cssSelector("input[id='phone_number'][class='field-phone-number d3ui-show d3ui-required']");
        //txtPhone_NumberSecondRow = By.cssSelector("input[id='phone_number-1'][class='field-phone-number d3ui-show error-field-true']");
        txtPhone_NumberSecondRow = By.xpath("//input[@id='phone_number-1']");
        //txtPhone_NumberSecondRow = By.cssSelector("input[id='phone_number-1'][contains(@class,'field-phone-number d3ui-show error-field']");
        txtPhone_NumberThirdRow = By.cssSelector("input[id='phone_number-2'][class='field-phone-number d3ui-show d3ui-required']");
        txtPhoneType = By.xpath("//*[@id='phone_type']");
        //txtPhoneType = By.cssSelector("select[id='phone_type'][class='field-phone-type d3ui-show d3ui-required']");
        //Locators To get the information from already populated fields
        lblMemberFirstName = By.id("mbr-firstname-text");
        lblMemberLastName = By.id("mbr-lastname-text");
        lblMemberNumberTxt = By.id("mbr-number-text");
        lblMemberZipCode = By.id("mbr-address-zip-text");
        lblMemberState = By.id("mbr-address-state-text");
        lblMemberCity = By.id("mbr-address-city-text");
        lblMemberNumberColumnValue = By.cssSelector("table[id=search-results] tr td[class=' member-number-column']");
        lblMemberContactColumnValue = By.cssSelector("table[id=search-results] tr td[class=' address-column']");
        lblMemberNameColumnValue = By.cssSelector("table[id=search-results] tr td[class=' last-name-column']");
        lblMemberAddressColumnValue = By.cssSelector("table[id=search-results] tr td[class=' phone-number-column']");
        //Error Locators
        alertUndefinedError = By.cssSelector("span[id*='ui-dialog-title-error-dialog-'] +a span");
        errorNotifications = By.cssSelector("div[id*='d3-notification-']");
        errorAlertOK = By.cssSelector("div[id*='error-dialog-'] + div div button span");
        saveFailureError = By.cssSelector("div[id*='error-dialog-'][class='error-dialog ui-dialog-content ui-widget-content']");
        errorNotification = By.className("d3ui-notification-message");
        lablMemberName = By.id(" last-name-column");
        //MemberDetails view section
        lblMemberShipNumber =By.id("mbr-number-text");
        lblMemberSince = By.id("mbr-since-text");
        lblMemberLevel = By.id("mbr-level-text");
        lblMemberType = By.id("mbr-type-text");
        lblMemberExpiration = By.id("mbr-expiration-text");
        lblMemberStatus = By.id("mbr-status-text");
        memberCallsAllowed=By.id("calls_allowed");
        memberCallsRemaining=By.id("calls_remaining");
        memberCallsUsed=By.id("calls-used-0");
        memberCurrentCalls=By.xpath("//*[@id='calls-current-0' or @id='calls-current-link'][contains(@class,'d3ui-show')]");
        memberChargeableCalls=By.xpath("//*[@id='calls-chargeable-0' or @id='calls-chargeable-link'][contains(@class,'d3ui-show')]");
        memberHistoryCalls=By.id("member-call-history");
        //Locators to populate the Member details manually
        txtTitle = By.id("mbr-title-input");
        txtFirstName = By.cssSelector("input[id='mbr-firstname-input'][class='d3ui-field d3ui-required']");
        txtLastName = By.cssSelector("input[id='mbr-lastname-input'][class='d3ui-field d3ui-required']");
        txtSuffix = By.cssSelector("input[id='mbr-suffix-input'][class='d3ui-field d3ui-optional']");
        txtAddressLine1 = By.cssSelector("input[id='mbr-address-line1-input'][class='d3ui-field d3ui-required']");
        txtAddressLine1_Error = By.cssSelector("input[id='mbr-address-line1-input'][class='d3ui-field d3ui-required ui-state-error ui-state-error-text d3ui-field-error']");
        txtAddressLine2 = By.cssSelector("input[id='mbr-address-line2-input'][class='d3ui-field']");
        txtCity = By.cssSelector("input[id='mbr-address-city-input'][class='d3ui-field d3ui-state-focus d3ui-required']");
        txtState = By.cssSelector("input[id='mbr-address-state-input'][class='d3ui-field d3ui-required']");
        txtZip = By.cssSelector("input[id='mbr-address-zip-input'][class='d3ui-field d3ui-required']");
        txtEmail = By.id("mbr-email-input");
        txtMemberNumber = By.cssSelector("input[id='mbr-number-input'][class='d3ui-field d3ui-required']");
        txtMbrSince = By.id("mbr-since-input");
        txtMemberLevel = By.cssSelector("input[id='mbr-level-input'][class='d3ui-field ui-autocomplete-input ui-corner-left d3ui-show d3ui-required']");
        txtMemberType = By.id("mbr-type-input");
        txtMemberExpiration = By.cssSelector("input[id='mbr-expiration-input'][class='d3ui-field hasDatepicker d3ui-required']");
        txtMemberStatus = By.cssSelector("input[id='mbr-status-input'][class='d3ui-field ui-autocomplete-input ui-corner-left d3ui-required']");
        txtMemberEmailId = By.id("mbr-email-input");
        radiobtnChangeOfAddress=By.id("mbr-address-changed-input");
        //Locators of MemberContactInformation section for editing the member phone number
        addPhoneButton = By.id("mbr-contact-add-btn");
        radiodbtnPrimRowOne = By.id("primary_phone");
        chkBoxTempCheckBoxRowOne = By.id("temp_checkbox");
        chkBoxTempCheckBoxRowThree = By.id("temp_checkbox-2");
        radiobtnPrimInRowThree=By.id("primary_phone-2");
        dropDownPhoneTypeRowThree = By.id("phone_type-2");
        addPhoneNumberTextFirstRow = By.xpath("//input[@id='phone_number']");
        addPhoneNumberTextThirdRow = By.id("phone_number-2");
        chkBoxDelCheckBoxSecondRow = By.id("del_checkbox-1");
        iconcurrentcallClose=By.cssSelector("div span[id='ui-dialog-title-callsactive-box'] +a span");
        rbutnprimary_phone= By.id("primary_phone");
        listOfCallsID=By.xpath("//tr[contains(@id,'active-')]/td[2]/a");
        btnClubCodeSearch=By.id("club-search-button");
        cityClubCode=By.xpath("//body/ul[12]/li/a");
        txtClubCode=By.id("club_code");
        btnSearchButton=By.id("search_button");
        listOfLastNames=By.className("last-name-column");
        txthonorific=By.id("mbr-title-input");
        lableExpirationDate=By.xpath("//div[@id='mbr-membershipdetails-fieldset']/div[5]/label");
        iconSearchCallClose=By.cssSelector("span[id='ui-dialog-title-call-search-dlg'] +a span");
        linkCallID=By.cssSelector("table[id='call-search-results-table'] tr a");
        expirationErrorMessageOKButton=By.xpath("/html/body/div[42]/div[3]/div/button/span");
        txtType=By.id("mbr-type-input");
        closeIconOnPartialCall=By.cssSelector("div [id='ui-dialog-title-confirmation-box']+a span");
        radiodbtnPrimRowTwo=By.id("primary_phone-1");
        txtSecondaryPhoneType=By.id("field_phone_ext-1");
        membershipRenewAlert=By.xpath("//div[@id='confirmation-box']");
        btnMembershipRenewNo=By.id("confirmation-no-btn");
        btnMembershipRenewYes=By.id("confirmation-yes-btn");
        radiobtnPrimInRowTwo=By.id("primary_phone-1");
        chkBoxSms=By.id("sms_checkbox-1");
        confirmationDialogQuestion=By.id("confirmation-dialog-question");
        btnYesOnConfirmationDialogQuestion= By.id("confirmation-yes-btn");
        btnNoOnConfirmationDialogQuestion=By.id("confirmation-no-btn");
        lblMemberCallId= By.xpath("(//span[@class='d3calls-widget-label d3ui-text-trim'])[1]");
        txtRapCallNumber=By.id("rap-call-number");
        txtRapPaymentResponsibilityCode=By.id("rap-payment-resp");
        clubCodeSelectionForRAPCall=By.xpath("//*[contains(@class, 'ui-corner-all')][contains(text(),'818')] ");
        txtLongTowAllowedValue=By.id("long_tow_allowed");
        lnkRapEntitlements=By.xpath("//div[@id='rap-entitlements-box']/h3/a[@id='warranty-selectwarrantybutton']");
        txtPhoneNumberFirstRecord =  By.xpath("//*[@id='phone_number-1']");
        txtPhoneTypeFirstRecord =  By.xpath("//*[@id='phone_type-1']");
        verifyMemberCompleteCheck = By.xpath("//*[@id='tab-member']//i[@class='tab-icon-complete icon-ok-sign']");
        linkCallSummaryIconOnMemberspage=By.xpath("//i[@class='icon-list-alt']");
        phoneNumberOnCallSummaryPOPUp=By.xpath("//span[@id='phone_number-hd-summary']");
        radiodbtnPrimRow = By.id("primary_phone-1");
        lblCdxAuthorizationLevel = By.id("cdx-auth-level");
        lblCdxAuthorizationMessage = By.id("cdx-auth-message");
        lblCdxAuthorizationCode = By.id("cdx-auth-code");
        lblCdxMotorCycleCoverage = By.id("cdx-motorcycle");
        errorServiceUnavailable=By.xpath("//div[contains(text(),'E302')]");
        errorCDXServiceUnavailable=By.xpath("//div[@class='error-dialog ui-dialog-content ui-widget-content']/div/div");
        txtLiveCall=By.xpath("//*[@id=\"d3calls-widget-call-info\"]/span[2]");
        lblMemberNameOnManualEntry=By.xpath("//div[@id='mbr-fullname-fieldset']/label[contains(text(),'Member Name:')]");
        lblAddressOnManualEntry=By.xpath("//div[@id='mbr-membershipdetails-fieldset-left']/div[1]/label[contains(text(),'Address:')]");
        lblAddress2OnManualEntry=By.xpath("//div[@id='mbr-membershipdetails-fieldset-left']//label[contains(text(),'Address2:')]");
        lblCityOnManualEntry=By.xpath("//div[@id='mbr-membershipdetails-fieldset-left']//label[contains(text(),'City:')]");
        lblStateOnManualEntry=By.xpath("//div[@id='mbr-membershipdetails-fieldset-left']//label[contains(text(),'State:')]");
        lblZipOnManualEntry=By.xpath("//div[@id='mbr-membershipdetails-fieldset-left']//label[contains(text(),'Zip:')]");
        lblMemberShipNumberOnManualEntry=By.xpath("//div[@id='member-data-right-column-container']//div[@class='d3ui-fielditem d3ui-show']//label[contains(text(),'Membership Number:')]");
        lblMemberSinceOnManualEntry=By.xpath("//div[@id='mbr-membershipdetails-fieldset']//label[contains(text(),'Member Since:')]");
        //lblMemberJoinDateOnManualEntry=By.xpath();
        lblLevelOnManualEntry=By.xpath("//div[@id='mbr-membershipdetails-fieldset']//label[contains(text(),'Level:')]");
        lblTypeOnManualEntry=By.xpath("//div[@id='mbr-membershipdetails-fieldset']//label[contains(text(),'Type:')]");
        lblExpirationOnManualEntry=By.xpath("//div[@id='mbr-membershipdetails-fieldset']//label[contains(text(),'Expiration:')]");
        lblStatusOnManualEntry=By.xpath("//div[@id='mbr-membershipdetails-fieldset']//label[contains(text(),'Status:')]");
        lblEmailOnManualEntry=By.xpath("//form[@id='mbr-email-form']//label[contains(text(),'E-mail Addres')]");
        lblPhoneInformationOnManualEntry=By.id("mbr-contact-title");
        listOfLoadedCalls=By.xpath("//table[@id='callsactive-table']/tbody//tr[contains(@class,'active-call')]");
        lnkcallIdOnLoadedCallList=By.cssSelector("table[id='callsactive-table'] tbody tr[id*='active-'] a");
        txtPhoneNumber = By.xpath("//input[contains(@id, 'phone_number-')]");
        lblDateInMemberPage = By.xpath("//*[@id='d3calls-widget-call-info']/span[2]");
    }
    public static By enterPhoneNumber(String phnnum) {
        String xpath = "//input[contains(@id, 'phone_number-"+phnnum+"')]";
        enterPhoneNumber = By.xpath(xpath);
        return enterPhoneNumber;
    }

    public static By clickPrimRadiobutton(String phnnum) {
        String id = "primary_phone-"+phnnum;
        clickPrimRadiobutton = By.id(id);
        return clickPrimRadiobutton;
    }

    public static By selectTempDeleteChkBox(String phnnum) {
        String id = "temp_checkbox-"+phnnum;
        selectTempDeleteChkBox = By.id(id);
        return selectTempDeleteChkBox;
    }

    public static By selectPhoneType(String phnnum) {
        String id = "phone_type-"+phnnum;
        selectPhoneType = By.id(id);
        return selectPhoneType;
    }




}
