package com.aaa.web.page;

import org.openqa.selenium.By;

public class CRSearchCallsPage {
    public static By btnSearch;
    public static By SelectRow;
    public static By txtRAPNumber;
    public static By txtFacility;
    public static By txtTruck;
    public static By txtCallTaker;
    public static By txtPhoneNumber;
    public static By txtClubSearch;
    public static By txtMemberLastNameSearch;
    public static By txtMemberNumberSearch;
    public static By txtYearVehicleInformation;
    public static By txtMakeVehicleInformation;
    public static By txtModelVehicleInformation;
    public static By txtLocation;
    public static By txtCity;
    public static By txtCallId;
    public static By txtStartTime;
    public static By txtEndTime;
    public static By btnClear;
    public static By dropdownSearchCalls;
    public static By linkSearchCalls;
    public static By searchResultFound;
    public static By btnSearchAgain;
    public static By callIDDetailsOnSearchCallsInSearclCallWindow;
    public static By MemberLastNameOnSearchCallsInSearclCallWindow;
    public static By ClubNumberOnSearchCallsInSearclCallWindow;
    public static By MemberNumberOnSearchCallsInSearclCallWindow;
    public static By LocationOnSearchCallsInSearclCallWindow;
    public static By CityOnSearchCallsInSearclCallWindow;
    public static By VehicleYearOnSearchCallsInSearclCallWindow;
    public static By VehicleMakeOnSearchCallsInSearclCallWindow;
    public static By VehicleModelOnSearchCallsInSearclCallWindow;
    public static By RAPOnSearchCallsInSearclCallWindow;
    public static By linkCallDateOnSearchCallsInSearclCallWindow;
    public static By phoneNumbersListOnSearchCallsInSearclCallWindow;
    public static By linkCallSummaryIconOnMemberspage;
    public static By phoneNumberOnCallSummaryPOPUp;
    public static By TruckIDDetailsOnSearchCallsInSearclCallWindow;
    public static By FacilityDetailsOnSearchCallsInSearclCallWindow;
    public static By txtStartDateOnSearchCallWindow;
    public static By lblDateInMemberPage;
    public static By clickOnCallIdLinkInSearchCalls;
    public static By txtStartDateInSearchCall;
    public static By txtEndDateInSearchCall;
    public static By txtMemberFirstNameSearch;
    public static By txtCommCenter;
    public static By invalidSearchCriteriaError;
    public static By okOnInvalidError;
    public static By dateInSearchCallsInSearclCallWindow;
    public static By txtNoMatchingRecords;
    public static By selectCallsType;
    public static By MemberLastNameOnSearchCallsInSearclCallWindowdynamically;
    public static By invalidSearchCriteriaErrorOnLiveOnly;
    public static By invalidSearchCriteriaErrorOnLiveAndArchive;
	public static By drpdwnCurrentCall;
	public static By lnkSendETARequest;
    public static By callIDDetailsOnRecentCallsInRecentCallWindow;
	public static By txtCallsInSearchCalls;
    public static By duplicateCallsIconInSearchCallWindow;
    public static By btnDuplicateYes;
    public static By btnDuplicateNo;
    public static By btnCloseSearchCalWindow;
    public static By linkRecentCalls;
    public static By callIDDetailsOnRecentCallsInSearclCallWindow;
    public static By duplicateCallsOnRecentCallsInSearclCallWindow;
    public static By  btnCloseSearchCall;
    public static By facilityErrorPopupMsg;
    public static By lnkCallIDOnSearchCalls;
    public static By lblNoMatchingRecords;
    public static By searchButtoninSearch;
    public static By txtMessageNoDataAvailableForSearchResults;
    public static By clickOnCallIdLink;
    public static By callSearchTypeDropdonArrow;
    public static By duplicateCallsIconRAPCallInSearchCallWindow;
    public static By duplicateCallsIconInSearchCallResultWindow;
    public static By lnkFirstCallIdInSearchResults;
    public static By lblMemberAndClubCodeOnSearchCallsTable;
    public static By CallType;
    public static By drpdwnCallType;
    public static By lnkSecondcallId;

    static {
        btnSearch = By.xpath("//*[@id=\"call-search-search-button\"]/span[contains(text(),'Search')]");
        SelectRow = By.xpath("//*[@id=\"call-search-results-table\"]/tbody/tr");
        txtRAPNumber=By.xpath("//*[@id='call-search-rap-number']");
        txtFacility=By.xpath("//*[@id='call-search-facility']");
        txtTruck=By.xpath("//*[@id='call-search-truck']");
        txtCallTaker=By.xpath("//*[@id='call-search-call-taker']");
        txtPhoneNumber=By.xpath("//*[@id='call-search-phone']");
        txtClubSearch=By.xpath("//*[@id='call-search-club-code']");
        txtMemberLastNameSearch =By.xpath("//*[@id='call-search-last-name']");
        txtMemberNumberSearch=By.xpath("//*[@id='call-search-member-number']");
        txtYearVehicleInformation=By.xpath("//*[@id='call-search-vehicle-year']");
        txtMakeVehicleInformation=By.xpath("//*[@id='call-search-vehicle-make']");
        txtModelVehicleInformation=By.xpath("//*[@id='call-search-vehicle-model']");
        txtLocation=By.xpath("//*[@id='call-search-breakdown-location']");
        txtCity=By.xpath("//*[@id='call-search-breakdown-city']");
        txtCallId=By.xpath("//*[@id='call-search-call-id']");
        txtStartTime=By.xpath("//*[@id='call-search-start-time']");
        txtEndTime=By.xpath("//*[@id='call-search-end-time']");
        btnClear=By.xpath("//button[@id='call-search-clear-button']");
        dropdownSearchCalls=By.xpath("//*[@id='application-content']/header/ul[1]/li[6]/a");
        //dropdownSearchCalls=By.xpath("//a[text()='Search Calls  ']");
        //dropdownSearchCalls=By.xpath("(//li[@class='d3ui-app-header-item d3ui-app-header-menu-item']/a/i)[2]");
        //dropdownSearchCalls=By.xpath("//a[@class='d3ui-menu-item-toggle d3ui-menu-toggle' and text()='Search Calls  ']");
        linkSearchCalls=By.id("search-calls-btn");
        searchResultFound=By.xpath("//tr[contains(@class,'odd call-search-result row-selected')]");
        btnSearchAgain=By.id("call-search-back-btn");
        callIDDetailsOnSearchCallsInSearclCallWindow=By.cssSelector("table[id='call-search-results-table'] tbody tr[id*='call-'] td:nth-child(2)");
        MemberLastNameOnSearchCallsInSearclCallWindow=By.cssSelector("table[id='call-search-results-table'] tbody tr[id*='call-'] td:nth-child(5)");
        ClubNumberOnSearchCallsInSearclCallWindow=By.cssSelector("table[id='call-search-results-table'] tbody tr[id*='call-'] td:nth-child(5)");
        MemberNumberOnSearchCallsInSearclCallWindow=By.cssSelector("table[id='call-search-results-table'] tbody tr[id*='call-'] td:nth-child(5)");
        LocationOnSearchCallsInSearclCallWindow=By.cssSelector("table[id='call-search-results-table'] tbody tr[id*='call-'] td:nth-child(7)");
        CityOnSearchCallsInSearclCallWindow=By.cssSelector("table[id='call-search-results-table'] tbody tr[id*='call-'] td:nth-child(7)");
        VehicleYearOnSearchCallsInSearclCallWindow=By.cssSelector("table[id='call-search-results-table'] tbody tr[id*='call-'] td:nth-child(6)");
        VehicleMakeOnSearchCallsInSearclCallWindow=By.cssSelector("table[id='call-search-results-table'] tbody tr[id*='call-'] td:nth-child(6)");
        VehicleModelOnSearchCallsInSearclCallWindow=By.cssSelector("table[id='call-search-results-table'] tbody tr[id*='call-'] td:nth-child(6)");
        RAPOnSearchCallsInSearclCallWindow=By.cssSelector("table[id='call-search-results-table'] tbody tr[id*='call-'] td:nth-child(9)");
        linkCallDateOnSearchCallsInSearclCallWindow=By.xpath("//a[@class='row-selection action-row-callback']");
        phoneNumbersListOnSearchCallsInSearclCallWindow=By.xpath("//table[@id='member-data-phone-table']//tbody/tr/td[1]");
        linkCallSummaryIconOnMemberspage=By.xpath("//i[@class='icon-list-alt']");
        phoneNumberOnCallSummaryPOPUp=By.xpath("//span[@id='phone_number-hd-summary']");
        TruckIDDetailsOnSearchCallsInSearclCallWindow=By.cssSelector("table[id='call-search-results-table'] tbody tr[id*='call-'] td:nth-child(8)");
        FacilityDetailsOnSearchCallsInSearclCallWindow=By.cssSelector("table[id='call-search-results-table'] tbody tr[id*='call-'] td:nth-child(8)");
        txtStartDateOnSearchCallWindow=By.xpath("//input[@id='call-search-start-date']");
        lblDateInMemberPage = By.xpath("//*[@id='d3calls-widget-call-info']/span[2]");
        clickOnCallIdLinkInSearchCalls = By.cssSelector("table[id='call-search-results-table'] tbody tr[id*='call-'] a");
        txtStartDateInSearchCall = By.xpath("//*[@id='call-search-start-date']");
        txtEndDateInSearchCall = By.xpath("//*[@id='call-search-end-date']");
        txtMemberFirstNameSearch =By.xpath("//*[@id='call-search-first-name']");
        txtCommCenter =By.xpath("//*[@id='call-search-comm-center']");
        invalidSearchCriteriaError=By.xpath("//div[contains(@class,'error')][text()='E200: Invalid Search Criteria: The Start Date must be before the End Date.']");
        okOnInvalidError=By.xpath("//span[contains(@class,'ui-button-text')][text()='OK']");
        dateInSearchCallsInSearclCallWindow=By.cssSelector("table[id='call-search-results-table'] tbody tr[id*='call-'] td:nth-child(2)");
        txtNoMatchingRecords=By.xpath("//*[@id='call-search-results-table']//td[@class='dataTables_empty']");
        selectCallsType=By.xpath("//input[@id='call-search-calls-type-select']");
        invalidSearchCriteriaErrorOnLiveOnly=By.cssSelector("div[class='ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix']+div[id*='error-dialog-'] div[class='d3ui-modal-icon d3ui-modal-icon-error']+div div");
        invalidSearchCriteriaErrorOnLiveAndArchive=By.cssSelector("div[class='ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix']+div[id*='error-dialog-'] div[class='d3ui-modal-icon d3ui-modal-icon-error']+div div");
        txtCallsInSearchCalls= By.id("call-search-calls-type-select");
        //duplicateCallsIconInSearchCallWindow= By.id("(//a[@class='d3ui-icon d3ui-icon-callduplicate action-duplicate-call'])[1]");
		drpdwnCurrentCall=By.xpath("//*[@id='application-content']/header/ul[1]/li[7]/a");
        lnkSendETARequest=By.cssSelector("#eta-request-wait-for-response a");
        linkRecentCalls = By.id("recent-calls-btn");
        callIDDetailsOnRecentCallsInRecentCallWindow = By.xpath("//table[@id='recent-calls-table']//tr[1]/td[1]/a");
        txtCallsInSearchCalls= By.id("call-search-calls-type-select");
        duplicateCallsIconRAPCallInSearchCallWindow= By.xpath("(//a[@class='d3ui-icon d3ui-icon-callduplicate action-duplicate-call'])[1]");
        duplicateCallsIconInSearchCallWindow= By.xpath("//td[9][string-length(text())=0]/../td[2]/a");

		btnDuplicateYes=By.id("confirmation-yes-btn");
		btnDuplicateNo=By.id("confirmation-no-btn");
		btnCloseSearchCalWindow=By.xpath("(//span[@class='ui-button-text' and text()='Close'])[5]");
		//linkRecentCalls=By.id("recent-calls-btn");
		callIDDetailsOnRecentCallsInSearclCallWindow=By.cssSelector("tbody tr[id*='recent'] td:nth-child(1)");
		duplicateCallsOnRecentCallsInSearclCallWindow=By.cssSelector("tbody tr[id*='recent'] td:nth-child(1)");
        btnCloseSearchCall=By.xpath("(//button[@id='call-search-close-btn'])[1]");
        facilityErrorPopupMsg=By.xpath("//div[@class='message']");
        lnkCallIDOnSearchCalls = By.xpath("//tr[@class='odd call-search-result row-selected lastsearchrecord']/td[2]/a");
        lblNoMatchingRecords=By.xpath(" //td[contains(@class,'dataTables_empty')][text()='No matching records found, try refining your search']");
        searchButtoninSearch = By.id("call-search-search-button");
        txtMessageNoDataAvailableForSearchResults= By.xpath("//*[@class='odd lastsearchrecord']//*[contains(text(),'No matching records found, try refining your search')]");
        clickOnCallIdLink = By.cssSelector("table[id='call-search-results-table'] tbody tr[id*='call-'] a");
        callSearchTypeDropdonArrow= By.xpath("//input[@id='call-search-calls-type-select']/../button");
        duplicateCallsIconInSearchCallResultWindow=By.xpath("//td[9][string-length(text())=0]/../td[10]/a");
        lnkFirstCallIdInSearchResults=By.xpath("//table[@id='call-search-results-table']/tbody/tr[1]/td[2]/a");
        lblMemberAndClubCodeOnSearchCallsTable=By.xpath("//table[@id='call-search-results-table']/tbody/tr[1]/td[5]");
        drpdwnCallType =By.xpath("//input[@id='call-search-calls-type-select']/../button");

    }

    public static By getFirstNameAndLastName(int t){
        String cssSelector="table[id='call-search-results-table'] tbody  tr[id*='call-']:nth-child("+t+") td:nth-child(5)";
        MemberLastNameOnSearchCallsInSearclCallWindowdynamically=By.cssSelector(cssSelector);
        return MemberLastNameOnSearchCallsInSearclCallWindowdynamically;
    }
    public static By selectCallType(String callType){
        String xpath="//a[contains(text(),'"+callType+"')]";
        CallType=By.xpath(xpath);
        return CallType;
    }
}
