package com.aaa.web.page;

import org.openqa.selenium.By;

public class CRVehicleTriagePage {
	
    public static By vehicleTriageTab;
    public static By txtVehicleType;
    public static By txtVehicleYear;
    public static By txtVehicleMake;
    public static By txtVehicleModel;
    public static By txtVehicleColor;
    public static By txtPacesetterCode;
    public static By doubleClickPaceCode;
    public static By errorAlertOK;
    public static By scriptError;
    public static By btnAlertSaveYes;
    public static By errorNotifications;
    public static By btnSave;
    public static By saveFailureError;
    public static By tabVehicletriage;
    public static By linkKeys;
    public static By rdBtnKeysissue;
    public static By txtPaceSetterCode;
    public static By linkVehicleModel;
    public static By txtVehicleSrch;
    public static By btnVehicleSrch;
    public static By linkAvailbleVehicleModel;
    public static By linkPacesetterCodeCancel;
    public static By txtPacesetterCodeManual;
    public static By btnDialogOkBtn;
    public static By dropboxVehicleType;
    public static By dropboxVehicleColor;
    public static By selcManualPacesetterCode;
    public static By selcManualPacesetterCodeTow;
    public static By txtTag;
    public static By linkBattery;
    public static By batteryProblem;
    public static By rdBtnBatteryIssue;
    public static By jumpStartRadioButton;
    public static By selcManualPacesetterCodeBattery;
    public static By selcManualPacesetterCodekey;
    public static By selectPacesetterCode;
    public static By btnFuel;
    public static By btnFlatTire;
    public static By rbtnOutOfGas;
    public static By rbtnDriverFrontSide;
    public static By rbtnClickYesOnSpareTire;
    public static By rbtnClickOnLockingLugNuts;
    public static By iconErrorPopup;
    public static By linkManualEntryLinkOnVehicleTriage;
    public static By selectVehicle;
    public static By vehicleDetailsTab;
    public static By lblSelectedPacesetterCodes;
    public static By btnCallSummary;
    public static By lblCallSummaryPaceSetterCodes;
    public static By txtVehicleSearch;
    public static By lnkVehicleSearch;
    public static By txtVehicleTrim;
    public static By txtVehicleTag;
    public static By txtVehicleState;
    public static By txtVehicleFlat;
    public static By txtVehicleNote;
    public static By btnMoreinfoTab;
    public static By txtMoreInfoTabSubType;
    public static By txtMoreInfoTabEngineType;
    public static By txtMoreInfoTabComment;
    public static By txtMoreInfoTabLength;
    public static By txtMoreInfoTabHeight;
    public static By txtMoreInfoTabWeight;
    public static By txtMoreInfoTabClass;
    public static By radioBtnLeftLightOnBattery;
    public static By lnkShortCuts;
    public static By iconCallSummary;
    public static By rbtnAirOnly;
    public static By lblSelectedPaceSetterCodes;
    public static By callSummaryPopUp;
    public static By lblPacesetterCodesInSummaryPopUp;
    public static By summaryPopUpCloseIcon;
    public static By iconTriageBeginArrow;
    public static By lblTriageQuestion;
    public static By lblPaceSetterNotSelected;
    public static By lnkVehicleSearchFilter;
    public static By lnkVehicleSearchIcon;
    public static By lnkClearAllFIelds;
    public static By lnkVehicleTypeSearchFromDropDown;
    public static By linVehicleModelSearchFromDropDown;
    public static By lnkClassFromMoreInfoTabFromDropDown;
    public static By iconCloseSelectedPaceSetterCode;
    public static By iconBeginTriageHere;
    public static By txtSelectedPaceSetterCodes;
    public static By rbtnCarStyleInKeys;
    public static By lnkSelectedPacesetterCodeFromDropDown;
    public static By iconCloseCallSummary;
    public static By iconCloseCallSummaryPopUpWindow;
    public static By rbtnOneTyreChangeDriverSideFront;
    public static By rbtnUnsure;
    public static By btnTow;
    public static By rbtnBrakeFailureOnTow;
    public static By rbtnFlatTyreNeedsAir;
    public static By btnBattery;
    public static By btnKeys;
    public static By rbtnBreakFailureOnTOWProblem;
    public static By btnProblemTypes;
    public static By rbtnProblemTypesOptions;
    public static By rbthBreakDownFailureForRVValue;
    public static By noPriorVehicles;
    public static By notificationCommentsSaved;
    public static By verifyVehicleTriageCompleteCheck;
    public static By linkVehicleInformation;
    public static By lblType;
    public static By lblYear;
    public static By lblMake;
    public static By lblModel;
    public static By lblTrim;
    public static By lblColor;
    public static By lblDriveline;
    public static By lblTag;
    public static By lblState;
    public static By lblFlat;
    public static By lblNote;
    public static By lblcallSummaryTroubleCodes;
    public static By lnkRAPTab;
    public static By txtVinOnRAPtab;
    public static By txtTriageComment;
    public static By btnAddTriageSection;
    public static By lblInvalidTextProvided;
    public static By lblYearInAfterClickOnSearchIocnInOmnibar;
    public static By lblMakeAndModelAterClickOnSearchIocnInOmnibar;
    public static By btnComment;
    public static By lblDateTime;
    public static By txtCommentedValue;
    public static By btnOkOnNearByAddressError;
    public static By btnAddSecondPaceSetterCode;
    public static By txtVehicleType_required;
    public static By txtVehicleYear_required;
    public static By txtVehicleMake_required;
    public static By txtVehicleModel_required;
    public static By txtVehicleColor_required;




    static {
        selcManualPacesetterCodekey=By.xpath("//a[contains(text(),'L701 Key Locked In Passenger Compartment')]");
        selcManualPacesetterCodeBattery=By.xpath("//a[contains(text(),'L302 No Crank - Bat Svc (non-AAA Bat)')]");
        //linkBattery=By.xpath("//*[@id='triage-group-tabs']/ul/li[1]/a");
        linkBattery=By.xpath("(//span[contains(@class,'d3icon-psc-ba')])");
        batteryProblem = By.id("BAPSQ001");
        rdBtnBatteryIssue=By.id("BAPSA001");
        selectPacesetterCode = By.xpath("//span[contains(@class,'tagit-label')]");
        jumpStartRadioButton = By.xpath("//*[contains(text(),'Jump start requested')]");
        linkVehicleModel=By.xpath("//*[@id='vi-vehicle-history-container']/li[2]");
        //linkVehiclemodel=By.xpath("//*[@id=\"vi-vehicle-history-container\"]//following::span[contains(text(),'2016 HONDA CITY (White)')]");
        vehicleTriageTab= By.xpath("//*[@id='tab-triage']");
        //vehicleTriageTab= By.xpath("(//span[contains(@class,'tab-link')])[3]");
        txtVehicleType_required = By.cssSelector("input[id='vi-type'][class='d3ui-field vehicle-field ui-autocomplete-input ui-corner-left d3ui-show d3ui-required']");
        txtVehicleType = By.cssSelector("input[id='vi-type']");
        txtVehicleYear_required = By.cssSelector("input[id='vi-year'][class='d3ui-field vehicle-field ui-autocomplete-input ui-corner-left d3ui-show d3ui-required']");
        txtVehicleYear = By.cssSelector("input[id='vi-year']");
        txtVehicleMake_required = By.cssSelector("input[id='vi-make'][class='d3ui-field vehicle-field ui-autocomplete-input ui-corner-left d3ui-show d3ui-required']");
        txtVehicleMake = By.cssSelector("input[id='vi-make']");
        txtVehicleModel_required = By.cssSelector("input[id='vi-model'][class='d3ui-field vehicle-field ui-autocomplete-input ui-corner-left d3ui-show d3ui-required']");
        txtVehicleModel = By.cssSelector("input[id='vi-model']");
        txtVehicleColor_required = By.cssSelector("input[id='vi-color'][class='d3ui-field vehicle-field ui-autocomplete-input ui-corner-left d3ui-show d3ui-required']");
        txtVehicleColor = By.cssSelector("input[id='vi-color']");
        txtPacesetterCode = By.xpath("//div[@id='triage-trouble-code-container']/ul/li/input");
        doubleClickPaceCode=By.id("triage-trouble-code-container");
        errorAlertOK =By.cssSelector("div[id*='error-dialog-'] + div div button span");
        scriptError =By.id("scripts-immediate-dialog-okayBtn");
        btnAlertSaveYes=By.id("confirmation-yes-btn");
        errorNotifications=By.cssSelector("div[id*='d3-notification-']");
        btnSave = By.id("save-call");
        btnAlertSaveYes=By.id("confirmation-yes-btn");
        saveFailureError = By.cssSelector("div[id*='error-dialog-'][class='error-dialog ui-dialog-content ui-widget-content']");
        tabVehicletriage=By.xpath("//*[@id=\"tab-triage\"]/span");
        txtVehicleSrch=By.id("vi-search-input");
        btnVehicleSrch=By.xpath("//*[@id='vi-search-btn']");
        linkAvailbleVehicleModel=By.xpath("//*[@id=\"vi-search-results\"]/tbody/tr/td[2]/a");
        linkKeys=By.xpath("//*[@id=\"triage-group-tabs\"]/ul/li[5]/a");
        rdBtnKeysissue=By.id("KEPSA001");
        //txtPaceSetterCode=By.xpath("//*[@id=\"triage-trouble-code-container\"]/ul/li[1]/span");
        txtPacesetterCodeManual=By.xpath("//*[@id='triage-trouble-code-container']/ul/li/input");
        btnDialogOkBtn=By.xpath("//*[@id=\"scripts-immediate-dialog-okayBtn\"]/span");
        dropboxVehicleType=By.cssSelector("input[id='vi-type']");
        dropboxVehicleColor=By.id("vi-color");
        selcManualPacesetterCode=By.xpath("//a[contains(text(),'L701 Key Locked In Passenger Compartment')]");
        selcManualPacesetterCodeTow=By.xpath("//a[contains(text(),'T880 Lock Issue Required Tow To Dealer')]");
        linkPacesetterCodeCancel=By.xpath("//*[@id=\"triage-trouble-code-container\"]/ul/li[1]/a/span[2]");
        txtTag=By.id("vi-tag");
        btnFuel = By.xpath("//*[@id='triage-group-tabs']//*[contains(text(),'Fuel')]");
        btnFlatTire = By.xpath("//*[@id='triage-group-tabs']//*[contains(text(),'Flat Tire')]");
        rbtnOutOfGas = By.xpath("//*[@id=\"FUPSQ001\"]/div[2]/div[1]/label[contains(text(),'Out of gas')]");
        rbtnDriverFrontSide = By.xpath("//*[@id=\"FTPSQ001\"]/div[2]/div[2]/label[contains(text(),'One tire change - driver side front')]");
        rbtnClickYesOnSpareTire = By.xpath("//*[@id=\"FTPSQ002\"]/div[2]/div[1]/label[contains(text(),'Yes')]");
        rbtnClickOnLockingLugNuts = By.xpath("//*[@id=\"FTPSQ003\"]/div[2]/div[4]/label[contains(text(),'Member')]");
        iconErrorPopup = By.cssSelector("div[id='scripts-immediate-dialog'] [id=confirmation-icon]");
        linkManualEntryLinkOnVehicleTriage=By.id("vi-manual-toggle-link");
        selectVehicle = By.xpath("//*[@id='vi-vehicle-history-container']/li[2]");
        vehicleDetailsTab=By.id("vehicle-details-tab");
        lblSelectedPacesetterCodes=By.xpath("//div[@id='triage-trouble-code-container']/ul/li[1]/span");
        btnCallSummary=By.xpath("//a[@title='Call Summary']/i");
        lblCallSummaryPaceSetterCodes=By.xpath("//*[@id='pacesetter1-hd-summary']");
        txtVehicleSearch=By.xpath("//*[@id='vi-search-input']");
        lnkVehicleSearch=By.xpath("//*[@id='vi-search-results']/tbody/tr/td[2]/a");
        txtVehicleTrim=By.xpath("//*[@id='vi-other-trim-level']");
        txtVehicleTag=By.xpath("//*[@id='vi-tag']");
        txtVehicleState=By.xpath("//*[@id='vi-state']");
        txtVehicleFlat=By.xpath("//*[@id='vi-flat']");
        txtVehicleNote=By.xpath("//*[@id='vi-other-note']");
        btnMoreinfoTab=By.xpath("//*[@id='additional-details-link']");
        txtMoreInfoTabSubType=By.xpath("//*[@id='vi-mc-type']");
        txtMoreInfoTabEngineType=By.xpath("//*[@id='vi-mc-eng-type']");
        txtMoreInfoTabComment=By.xpath("//*[@id='vi-mc-comment']");
        txtMoreInfoTabLength=By.xpath("//*[@id='vi-rv-length']");
        txtMoreInfoTabHeight=By.xpath("//*[@id='vi-rv-height']");
        txtMoreInfoTabWeight=By.xpath("//*[@id='vi-rv-weight']");
        txtMoreInfoTabClass=By.xpath("//*[@id='vi-rv-class']");
        radioBtnLeftLightOnBattery=By.id("BAPSA002");
        lnkShortCuts = By.xpath("//span[contains(@class,'d3icon-psc-sc')]");
        iconCallSummary = By.xpath("//div[@class='aux-buttons']//a[@class='aux-callsummary']");
        rbtnAirOnly = By.id("FTPSA001");
        lblSelectedPaceSetterCodes = By.xpath("//span[@class='tagit-label']");
        callSummaryPopUp =  By.id("ui-dialog-title-call-summary-dialog");
        lblPacesetterCodesInSummaryPopUp = By.xpath("//span[@id='pacesetter1-hd-summary']");
        summaryPopUpCloseIcon  = By.xpath("//span[@class='ui-icon ui-icon-closethick']");
        iconTriageBeginArrow   = By.id("triage-begin-arrow");
        lblTriageQuestion = By.xpath("//a[@class='triage-question-toggle ui-icon ui-icon-triangle-1-s']/following-sibling::div[1]");
        lblPaceSetterNotSelected = By.id("triage-no-tc-selected");
        lnkVehicleSearchFilter=By.xpath("//*[@id='vi-search-results']/tbody/tr/td[2]");
        lnkVehicleSearchIcon=By.xpath("//*[@id='vi-search-btn']");
        lnkClearAllFIelds=By.xpath("//*[@id='clear-vehicle-btn']");
        lnkVehicleTypeSearchFromDropDown =By.xpath("//ul[17]/li[1]/a");
        linVehicleModelSearchFromDropDown = By.xpath("//ul[20]/li/a");
        lnkClassFromMoreInfoTabFromDropDown=By.xpath("//ul[30]/li/a");
        iconCloseSelectedPaceSetterCode = By.xpath("//a[@class='tagit-close']");
        iconBeginTriageHere = By.id("triage-begin-arrow");
        txtSelectedPaceSetterCodes = By.xpath("//*[@id='triage-trouble-code-container']/ul/li/input");
        rbtnCarStyleInKeys = By.xpath("//*[@id='KER1Q001']/div[2]/div[1]/label[contains(text(),'Car')]");
        lnkSelectedPacesetterCodeFromDropDown=By.xpath("//a[@class='ui-corner-all']");
        iconCloseCallSummary=By.cssSelector("span[id='ui-dialog-title-call-summary-dialog']+a");
        iconCloseCallSummaryPopUpWindow= By.xpath("//div[contains(text(),'Caller Info')]/../../preceding-sibling::div/a");
        rbtnOneTyreChangeDriverSideFront = By.id("FTPSA002");
        rbtnUnsure = By.id("FTPSA011");
        btnTow=By.xpath("//*[@id='triage-group-tabs']/ul/li[7]/a");
        rbtnBrakeFailureOnTow = By.xpath("//*[@id='TOPSQ001']/div[2]/div[1]/label[contains(text(),'Brake failure')]");
        rbtnFlatTyreNeedsAir = By.id("FT3MA001");
        btnBattery=By.cssSelector("div[id='triage-group-tabs'] ul li:nth-child(1)");
        btnKeys=By.cssSelector("div[id='triage-group-tabs'] ul li:nth-child(5)");
        rbtnBreakFailureOnTOWProblem=By.id("TOPSA001");
        rbthBreakDownFailureForRVValue=By.id("TOR1Q001");
        noPriorVehicles = By.xpath("//*[contains(text(),'Prior known vehicles are not available')]");
        notificationCommentsSaved = By.className("d3ui-notification-title");
        verifyVehicleTriageCompleteCheck = By.xpath("//*[@id='tab-triage']//i[@class='tab-icon-complete icon-ok-sign']");
        linkVehicleInformation=By.xpath("//*[@id='vi-vehicle-history-container']/li[2]/span[2]");
        lblType=By.xpath("//*[@id='vi-vehicle-table']//*[contains(text(),'Type')]");
        lblYear=By.xpath("//*[@id='vi-vehicle-table']//*[contains(text(),'Year')]");
        lblMake=By.xpath("//*[@id='vi-vehicle-table']//*[contains(text(),'Make')]");
        lblModel=By.xpath("//*[@id='vi-vehicle-table']//*[contains(text(),'Model')]");
        lblTrim=By.xpath("//*[@id='vi-vehicle-table']//*[contains(text(),'Trim')]");
        lblColor=By.xpath("//*[@id='vi-vehicle-table']//*[contains(text(),'Color')]");
        lblDriveline=By.xpath("//*[@id='vi-vehicle-table']//*[contains(text(),'Driveline')]");
        lblTag=By.xpath("//*[@id='vi-vehicle-table']//*[contains(text(),'Tag')]");
        lblState=By.xpath("//*[@id='vi-vehicle-table']//*[contains(text(),'State')]");
        lblFlat=By.xpath("//*[@id='vi-vehicle-table']//*[contains(text(),'Flat')]");
        lblNote=By.xpath("//*[@id='vi-vehicle-table']//*[contains(text(),'Note')]");
        lblcallSummaryTroubleCodes=By.xpath("//*[@id='pacesetter-trouble-code1-hd-summary']");
        lnkRAPTab=By.id("rap-link");
        txtVinOnRAPtab=By.id("vi-vin");
        txtTriageComment = By.id("triage-comment-input");
        btnAddTriageSection = By.id("triage-comment-okay-btn");
        lblInvalidTextProvided = By.className("formErrorContent");

        btnComment=By.xpath("//button[@id='view-comments-btn']");
        lblDateTime=By.xpath("(//a[contains(@class,'comment-time')])[1]");
        txtCommentedValue=By.xpath("(//textarea[contains(@name,'comment')])[1]");
        btnAddSecondPaceSetterCode = By.id("triage-add-trouble-code-btn");
        btnOkOnNearByAddressError=By.xpath("(//span[contains(text(),'OK')])");
        lblYearInAfterClickOnSearchIocnInOmnibar=By.xpath("//*[@id='vi-search-results']//td[1]");
        lblMakeAndModelAterClickOnSearchIocnInOmnibar=By.xpath("//*[@id='vi-search-results']//td[2]/a");

    }
    public static By btnProblemTypes(String problemtype) {
        String xpath = "//div[@id='triage-group-tabs']//span[contains(text(),'"+problemtype+"')]";
        btnProblemTypes = By.xpath(xpath);
        return btnProblemTypes;
    }

    public static By rbtnProblemTypesOptions(String problemtypeoptions) {
        String xpath = "//input[not(@disabled)]/../label[contains(text(),'"+problemtypeoptions+"')]";
        rbtnProblemTypesOptions = By.xpath(xpath);
        return rbtnProblemTypesOptions;
    }

}
